/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author michi
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pswPassword = new javax.swing.JPasswordField();
        chbMostraPassword = new javax.swing.JCheckBox();
        btnEntra = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pswPassword.setText("PASSWORD - PASSWORD");
        pswPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pswPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 280, 40));

        chbMostraPassword.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        chbMostraPassword.setForeground(new java.awt.Color(240, 240, 240));
        chbMostraPassword.setText("Mostra Password");
        chbMostraPassword.setContentAreaFilled(false);
        chbMostraPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMostraPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(chbMostraPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 240, 40));

        btnEntra.setBackground(new java.awt.Color(0, 0, 0));
        btnEntra.setIcon(new javax.swing.ImageIcon("C:\\Users\\michi\\Desktop\\Itis - Galileo Galilei\\Anno Scolastico 2020-2021\\OrientaDay\\OrientaDay\\src\\bottone.png")); // NOI18N
        btnEntra.setContentAreaFilled(false);
        getContentPane().add(btnEntra, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 160, 60));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\michi\\Desktop\\Itis - Galileo Galilei\\Anno Scolastico 2020-2021\\OrientaDay\\OrientaDay\\src\\Pagina 1.png")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbMostraPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMostraPasswordActionPerformed
        // TODO add your handling code here:
        if(chbMostraPassword.isSelected()){
            pswPassword.setEchoChar((char)0); 
        }
        else{
            pswPassword.setEchoChar('*');
        }
        
    }//GEN-LAST:event_chbMostraPasswordActionPerformed

    private void pswPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswPasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pswPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnEntra;
    private javax.swing.JCheckBox chbMostraPassword;
    private javax.swing.JPasswordField pswPassword;
    // End of variables declaration//GEN-END:variables
}
